### ISSUE TITLE
Selecting after clicking the searched result (via mouse) is not loading the zombie/plants

### ISSUE THREAD

**Issue by ShrihariMohan** [code-cracked/plants-vs-zombies-api#22]
https://user-images.githubusercontent.com/60439461/151201969-7b8e78ef-0445-49c6-abd3-9fdaf033bb5e.mov

Selecting the result via mouse is not loading the content. Instead have to press enter in keyboard. Also having arrow keys up and down events to navigate the searched result will be great.

Let me know if i can contribute to this (my fav childhood game , still playing) project.

**Comment by Dani-Hacker** [comment]
Yes you can start working on it, that would be a nice addition to the website. I have assigned it to you. Please keep sharing your progress regularly, preferrably every 3-4 days.

**Comment by ShrihariMohan** [comment]
Sure , I am actually working. So I will start this weekend.

**Comment by daniel-jebarson** [comment]
@ShrihariMohan Thank you for your contribution in our project i have merged your pull request to main branch. We will add your name in contributor list soon.
