### ISSUE TITLE
Inconsistency in properties

### ISSUE THREAD

**Issue by AngelPalomar** [code-cracked/plants-vs-zombies-api#36]
Hello, just mencioning the properties name doesn't are equal in all. 

![image](https://user-images.githubusercontent.com/60854322/228996600-db2e84eb-0dfe-4977-98b5-884dbd45fd25.png)

Thanks!

**Comment by daniel-jebarson** [comment]
Thank you for reporting the issue, we will look into it

**Comment by daniel-jebarson** [comment]
The incosistency in data issue has been fixed please check now (:
